# Generated by Django 4.0.3 on 2022-07-07 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('message', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastname', models.CharField(max_length=300)),
                ('firstname', models.CharField(max_length=300)),
                ('middlename', models.CharField(max_length=300)),
                ('contact', models.IntegerField()),
                ('email', models.EmailField(blank=True, default='', max_length=254, null=True)),
                ('street', models.CharField(max_length=200)),
                ('subd', models.CharField(max_length=200)),
                ('brgy', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('zipcode', models.IntegerField()),
                ('soapname', models.CharField(max_length=300)),
                ('qty', models.CharField(max_length=300)),
            ],
        ),
    ]
